use_directory_urls: false
site_url: "https://dautovicharis.github.io/charts/"

site_name: "Charts"
site_description: "Documentation for the Charts Kotlin Multiplatform library"
site_author: "Haris Dautović"

repo_name: "dautovicharis/charts"
repo_url: "https://github.com/dautovicharis/charts"
edit_uri: "edit/main/docs/docs/"

theme:
    name: 'material'
    features:
        - navigation.expand
        - search.highlight
        - search.share
        - content.code.copy

    # Syntax highlighting
    highlightjs: true
    hljs_languages:
        - kotlin
        - groovy
        - gradle
        - xml
        - yaml
    palette:
        # Light mode
        - media: "(prefers-color-scheme: light)"
          scheme: default
          primary: indigo
          accent: indigo
          toggle:
            icon: material/brightness-7
            name: Switch to dark mode
        # Dark mode
        - media: "(prefers-color-scheme: dark)"
          scheme: slate
          primary: indigo
          accent: indigo
          toggle:
            icon: material/brightness-4
            name: Switch to light mode
    icon:
        repo: fontawesome/brands/github
        logo: material/chart-line

docs_dir: "src"
site_dir: "./public-site"

# Navigation
nav:
  - Home: index.md
  - Getting Started: getting-started.md
  - Examples: examples.md
  - JS Demo: jsdemo/index.html
  - API:
      - 2.0.0: ../2.0.0/api/index.html
      - 2.0.1-SNAPSHOT: ../2.0.1-SNAPSHOT/api/index.html

# Markdown extensions
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

# Extra configuration
extra:
  version:
    provider: mike
    default: latest
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/dautovicharis/charts

