name: Build

on:
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: ci-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: 'zulu'
          cache: gradle
      - name: Build
        run: ./gradlew assemble
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: docs/docs-app/package-lock.json
      - name: Install docs app dependencies
        working-directory: docs/docs-app
        run: npm ci
      - name: Build docs app
        working-directory: docs/docs-app
        run: npm run build
